// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Platform.DataAccess.Postgress;

#nullable disable

namespace Platform.DataAccess.Postgress.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260614205357_AddCourseInstancesAndEducationalGroups")]
    partial class AddCourseInstancesAndEducationalGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementConnectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("SourceId", "TargetId")
                        .IsUnique();

                    b.ToTable("achievement_connections", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementCriteriaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("uuid");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID")
                        .IsUnique();

                    b.ToTable("achievement_criterias", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("LabID")
                        .HasColumnType("uuid");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Common");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Track")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("default");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("LabID");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEntity")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContentScopeID")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreviousID")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentScopeID")
                        .IsUnique();

                    b.HasIndex("PreviousID");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseInstanceEntity", b =>
                {
                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<Guid>("ContentScopeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CourseID", "Year");

                    b.HasIndex("ContentScopeID")
                        .IsUnique();

                    b.ToTable("course_instances", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseInstanceStudentEntity", b =>
                {
                    b.Property<Guid>("CourseID")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CourseID", "Year", "PersonID");

                    b.HasIndex("PersonID");

                    b.ToTable("course_instance_students", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.EducationalGroupEntity", b =>
                {
                    b.Property<string>("GroupName")
                        .HasColumnType("text");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("integer");

                    b.Property<Guid>("EdProgramID")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GroupCaption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupName");

                    b.ToTable("educational_groups", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.GroupStudentEntity", b =>
                {
                    b.Property<Guid>("PersonID")
                        .HasColumnType("uuid");

                    b.Property<string>("EdGroupID")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PersonID", "EdGroupID", "StartDate");

                    b.HasIndex("EdGroupID");

                    b.ToTable("group_students", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentAchievementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AchievementFoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AchievementGotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AchievementID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFirstAnimationShown")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotificationSeen")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LabID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AchievementID");

                    b.HasIndex("LabID");

                    b.HasIndex("StudentID", "AchievementID")
                        .IsUnique();

                    b.ToTable("student_achievements", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementConnectionEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementCriteriaEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Achievement")
                        .WithOne("Criteria")
                        .HasForeignKey("Platform.DataAccess.Postgress.AchievementCriteriaEntity", "AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.CourseEntity", "Course")
                        .WithMany("Achievements")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.CourseEntity", "PreviousCourse")
                        .WithMany()
                        .HasForeignKey("PreviousID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviousCourse");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseInstanceEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.CourseEntity", "Course")
                        .WithMany("Instances")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseInstanceStudentEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.StudentEntity", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.CourseInstanceEntity", "CourseInstance")
                        .WithMany("Students")
                        .HasForeignKey("CourseID", "Year")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseInstance");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.GroupStudentEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.EducationalGroupEntity", "EducationalGroup")
                        .WithMany("Students")
                        .HasForeignKey("EdGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.StudentEntity", "Student")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EducationalGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentAchievementEntity", b =>
                {
                    b.HasOne("Platform.DataAccess.Postgress.AchievementEntity", "Achievement")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Platform.DataAccess.Postgress.StudentEntity", "Student")
                        .WithMany("StudentAchievements")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.AchievementEntity", b =>
                {
                    b.Navigation("Criteria")
                        .IsRequired();

                    b.Navigation("StudentAchievements");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseEntity", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.CourseInstanceEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.EducationalGroupEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Platform.DataAccess.Postgress.StudentEntity", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("GroupMemberships");

                    b.Navigation("StudentAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
